@Nookly.Api_HostAddress = http://localhost:5186

GET {{Nookly.Api_HostAddress}}/health
Accept: application/json

###

GET {{Nookly.Api_HostAddress}}/api/media
Accept: application/json

###

POST {{Nookly.Api_HostAddress}}/api/media
Content-Type: application/json

{
  "title": "Dune",
  "type": "Movie",
  "description": "Science fiction"
}
